package com.revature.entity;
// Generated Nov 7, 2017 9:24:46 PM by Hibernate Tools 5.2.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TfBatchLocation generated by hbm2java
 */
@Entity
@Table(name = "TF_BATCH_LOCATION", schema = "ADMIN")
public class TfBatchLocation implements java.io.Serializable {

	private static final long serialVersionUID = -213863298550515723L;
	
	private BigDecimal tfBatchLocationId;

	private String tfBatchLocationName;
	
	private Set<TfBatch> tfBatches = new HashSet<TfBatch>(0);

	public TfBatchLocation() {
	}

	public TfBatchLocation(BigDecimal tfBatchLocationId) {
		this.tfBatchLocationId = tfBatchLocationId;
	}

	public TfBatchLocation(BigDecimal tfBatchLocationId, String tfBatchLocationName, Set<TfBatch> tfBatches) {
		this.tfBatchLocationId = tfBatchLocationId;
		this.tfBatchLocationName = tfBatchLocationName;
		this.tfBatches = tfBatches;
	}

	@Id

	@Column(name = "TF_BATCH_LOCATION_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getTfBatchLocationId() {
		return this.tfBatchLocationId;
	}

	public void setTfBatchLocationId(BigDecimal tfBatchLocationId) {
		this.tfBatchLocationId = tfBatchLocationId;
	}

	@Column(name = "TF_BATCH_LOCATION_NAME", length = 500)
	public String getTfBatchLocationName() {
		return this.tfBatchLocationName;
	}

	public void setTfBatchLocationName(String tfBatchLocationName) {
		this.tfBatchLocationName = tfBatchLocationName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tfBatchLocation")
	public Set<TfBatch> getTfBatches() {
		return this.tfBatches;
	}

	public void setTfBatches(Set<TfBatch> tfBatches) {
		this.tfBatches = tfBatches;
	}

//	@Override
//	public String toString() {
//		return "TfBatchLocation [tfBatchLocationId=" + tfBatchLocationId + ", tfBatchLocationName="
//				+ tfBatchLocationName + ", tfBatches=" + tfBatches + "]";
//	}
	
	

}
