package com.revature.entity;
// Generated Nov 2, 2017 9:19:06 AM by Hibernate Tools 5.2.5.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TfBatch generated by hbm2java
 */
@Entity
@Table(name = "TF_BATCH", schema = "ADMIN")
public class TfBatch implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1981150396737240585L;
	private BigDecimal tfBatchId;
	private TfClient tfClient;
	private TfCurriculum tfCurriculum;
	private TfBatchLocation tfBatchLocation;
	private String tfBatchName;
	private Serializable tfBatchStartDate;
	private Serializable tfBatchEndDate;
	private Set<TfAssociate> tfAssociates = new HashSet<TfAssociate>(0);

	public TfBatch() {
	}

	public TfBatch(BigDecimal tfBatchId) {
		this.tfBatchId = tfBatchId;
	}

	public TfBatch(BigDecimal tfBatchId, TfClient tfClient, TfCurriculum tfCurriculum, TfBatchLocation tfBatchLocation,
			String tfBatchName, Serializable tfBatchStartDate, Serializable tfBatchEndDate,
			Set<TfAssociate> tfAssociates) {
		this.tfBatchId = tfBatchId;
		this.tfClient = tfClient;
		this.tfCurriculum = tfCurriculum;
		this.tfBatchLocation = tfBatchLocation;
		this.tfBatchName = tfBatchName;
		this.tfBatchStartDate = tfBatchStartDate;
		this.tfBatchEndDate = tfBatchEndDate;
		this.tfAssociates = tfAssociates;
	}

	@Id

	@Column(name = "TF_BATCH_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getTfBatchId() {
		return this.tfBatchId;
	}

	public void setTfBatchId(BigDecimal tfBatchId) {
		this.tfBatchId = tfBatchId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TF_CLIENT_ID")
	public TfClient getTfClient() {
		return this.tfClient;
	}

	public void setTfClient(TfClient tfClient) {
		this.tfClient = tfClient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TF_CURRICULUM_ID")
	public TfCurriculum getTfCurriculum() {
		return this.tfCurriculum;
	}

	public void setTfCurriculum(TfCurriculum tfCurriculum) {
		this.tfCurriculum = tfCurriculum;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TF_BATCH_LOCATION_ID")
	public TfBatchLocation getTfBatchLocation() {
		return this.tfBatchLocation;
	}

	public void setTfBatchLocation(TfBatchLocation tfBatchLocation) {
		this.tfBatchLocation = tfBatchLocation;
	}

	@Column(name = "TF_BATCH_NAME", length = 30)
	public String getTfBatchName() {
		return this.tfBatchName;
	}

	public void setTfBatchName(String tfBatchName) {
		this.tfBatchName = tfBatchName;
	}

	@Column(name = "TF_BATCH_START_DATE")
	public Serializable getTfBatchStartDate() {
		return this.tfBatchStartDate;
	}

	public void setTfBatchStartDate(Serializable tfBatchStartDate) {
		this.tfBatchStartDate = tfBatchStartDate;
	}

	@Column(name = "TF_BATCH_END_DATE")
	public Serializable getTfBatchEndDate() {
		return this.tfBatchEndDate;
	}

	public void setTfBatchEndDate(Serializable tfBatchEndDate) {
		this.tfBatchEndDate = tfBatchEndDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tfBatch")
	public Set<TfAssociate> getTfAssociates() {
		return this.tfAssociates;
	}

	public void setTfAssociates(Set<TfAssociate> tfAssociates) {
		this.tfAssociates = tfAssociates;
	}

}
