package com.revature.entity;
// Generated Nov 2, 2017 9:19:06 AM by Hibernate Tools 5.2.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TfEndClient generated by hbm2java
 */
@Entity
@Table(name = "TF_END_CLIENT", schema = "ADMIN")
public class TfEndClient implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8175414335191263880L;
	private BigDecimal tfEndClientId;
	private String tfEndClientName;
	private Set<TfPlacement> tfPlacements = new HashSet<TfPlacement>(0);
	private Set<TfInterview> tfInterviews = new HashSet<TfInterview>(0);

	public TfEndClient() {
	}

	public TfEndClient(BigDecimal tfEndClientId) {
		this.tfEndClientId = tfEndClientId;
	}

	public TfEndClient(BigDecimal tfEndClientId, String tfEndClientName, Set<TfPlacement> tfPlacements,
			Set<TfInterview> tfInterviews) {
		this.tfEndClientId = tfEndClientId;
		this.tfEndClientName = tfEndClientName;
		this.tfPlacements = tfPlacements;
		this.tfInterviews = tfInterviews;
	}

	@Id

	@Column(name = "TF_END_CLIENT_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getTfEndClientId() {
		return this.tfEndClientId;
	}

	public void setTfEndClientId(BigDecimal tfEndClientId) {
		this.tfEndClientId = tfEndClientId;
	}

	@Column(name = "TF_END_CLIENT_NAME", length = 30)
	public String getTfEndClientName() {
		return this.tfEndClientName;
	}

	public void setTfEndClientName(String tfEndClientName) {
		this.tfEndClientName = tfEndClientName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tfEndClient")
	public Set<TfPlacement> getTfPlacements() {
		return this.tfPlacements;
	}

	public void setTfPlacements(Set<TfPlacement> tfPlacements) {
		this.tfPlacements = tfPlacements;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tfEndClient")
	public Set<TfInterview> getTfInterviews() {
		return this.tfInterviews;
	}

	public void setTfInterviews(Set<TfInterview> tfInterviews) {
		this.tfInterviews = tfInterviews;
	}

}
