package com.revature.entity;
// Generated Nov 7, 2017 9:24:46 PM by Hibernate Tools 5.2.5.Final

import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TfInterview generated by hbm2java
 */
@Entity
@Table(name = "TF_INTERVIEW", schema = "ADMIN")
public class TfInterview implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4148475604579144144L;
	@Id
	@Column(name = "TF_INTERVIEW_ID", unique = true, nullable = false, precision = 22, scale = 0)
	private Integer tfInterviewId;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TF_ASSOCIATE_ID")
	private TfAssociate tfAssociate;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TF_CLIENT_ID")
	private TfClient tfClient;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TF_END_CLIENT_ID")
	private TfEndClient tfEndClient;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TF_INTERVIEW_TYPE_ID")
	private TfInterviewType tfInterviewType;
	@Column(name = "TF_INTERVIEW_DATE")
	private Timestamp tfInterviewDate;
	//private String tfInterviewFeedback;

	// 1804
	@Column(name = "TF_ASSOCIATE_FEEDBACK", length = 2000)
	private String associateFeedback;
	@Column(name = "TF_ASSOCIATE_FEEDBACK", length = 2000)
	private String clientFeedback;
	@Column(name = "TF_ASSOCIATE_FEEDBACK", length = 2000)
	private String jobDescription;
	@Column(name = "TF_ASSOCIATE_FEEDBACK", length = 2000)
	private Timestamp dateSalesIssued;
	@Column(name = "TF_ASSOCIATE_FEEDBACK")
	private Timestamp dateAssociateIssued;
	@Column(name = "TF_ASSOCIATE_FEEDBACK")
	private Integer isInterviewFlagged;
	@Column(name = "TF_ASSOCIATE_FEEDBACK")
	private String flagReason;
	@Column(name = "TF_ASSOCIATE_FEEDBACK")
	private Integer isClientFeedbackVisiable;

	public TfInterview() {
	}

	public TfInterview(Integer tfInterviewId) {
		this.tfInterviewId = tfInterviewId;
	}

	public TfInterview(Integer tfInterviewId, TfAssociate tfAssociate, TfClient tfClient, TfEndClient tfEndClient,
			TfInterviewType tfInterviewType, Timestamp tfInterviewDate, String associateFeedback, String clientFeedback,
					   String jobDescription, Timestamp dateSalesIssued, Timestamp dateAssociateIssued, Integer isInterviewFlagged,
					   String flagReason, Integer isClientFeedbackVisiable) {
		this.tfInterviewId = tfInterviewId;
		this.tfAssociate = tfAssociate;
		this.tfClient = tfClient;
		this.tfEndClient = tfEndClient;
		this.tfInterviewType = tfInterviewType;
		this.tfInterviewDate = tfInterviewDate;

		this.associateFeedback = associateFeedback;
		this.clientFeedback = clientFeedback;
		this.jobDescription = jobDescription;
		this.dateSalesIssued = dateSalesIssued;
		this.dateAssociateIssued = dateAssociateIssued;
		this.isInterviewFlagged = isInterviewFlagged;
		this.flagReason = flagReason;
		this.isClientFeedbackVisiable = isClientFeedbackVisiable;
	}

	public Integer getTfInterviewId() {
		return this.tfInterviewId;
	}

	public void setTfInterviewId(Integer tfInterviewId) {
		this.tfInterviewId = tfInterviewId;
	}

	public TfAssociate getTfAssociate() {
		return this.tfAssociate;
	}

	public void setTfAssociate(TfAssociate tfAssociate) {
		this.tfAssociate = tfAssociate;
	}

	public TfClient getTfClient() {
		return this.tfClient;
	}

	public void setTfClient(TfClient tfClient) {
		this.tfClient = tfClient;
	}

	public TfEndClient getTfEndClient() {
		return this.tfEndClient;
	}

	public void setTfEndClient(TfEndClient tfEndClient) {
		this.tfEndClient = tfEndClient;
	}

	public TfInterviewType getTfInterviewType() {
		return this.tfInterviewType;
	}

	public void setTfInterviewType(TfInterviewType tfInterviewType) {
		this.tfInterviewType = tfInterviewType;
	}

	public Timestamp getTfInterviewDate() {
		return this.tfInterviewDate;
	}

	public void setTfInterviewDate(Timestamp tfInterviewDate) {
		this.tfInterviewDate = tfInterviewDate;
	}

	public String getTfInterviewFeedback() {
		return this.tfInterviewFeedback;
	}

	public void setTfInterviewFeedback(String tfInterviewFeedback) {
		this.tfInterviewFeedback = tfInterviewFeedback;
	}
	
	public void setTfEndClientName(String name) {
		this.tfEndClient.setTfEndClientName(name);
	}

}
