package com.revature.entity;
// Generated Nov 7, 2017 9:24:46 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TfMarketingStatus generated by hbm2java
 */
@Entity
@Table(name = "TF_MARKETING_STATUS", schema = "ADMIN")
public class TfMarketingStatus implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1638800519652509525L;
	private Integer tfMarketingStatusId;
	private String tfMarketingStatusName;
	private Set<TfAssociate> tfAssociates = new HashSet<TfAssociate>(0);

	public TfMarketingStatus() {
	}

	public TfMarketingStatus(Integer tfMarketingStatusId) {
		this.tfMarketingStatusId = tfMarketingStatusId;
	}

	public TfMarketingStatus(Integer tfMarketingStatusId, String tfMarketingStatusName,
			Set<TfAssociate> tfAssociates) {
		this.tfMarketingStatusId = tfMarketingStatusId;
		this.tfMarketingStatusName = tfMarketingStatusName;
		this.tfAssociates = tfAssociates;
	}

	@Id

	@Column(name = "TF_MARKETING_STATUS_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getTfMarketingStatusId() {
		return this.tfMarketingStatusId;
	}

	public void setTfMarketingStatusId(Integer tfMarketingStatusId) {
		this.tfMarketingStatusId = tfMarketingStatusId;
	}

	@Column(name = "TF_MARKETING_STATUS_NAME", length = 30)
	public String getTfMarketingStatusName() {
		return this.tfMarketingStatusName;
	}

	public void setTfMarketingStatusName(String tfMarketingStatusName) {
		this.tfMarketingStatusName = tfMarketingStatusName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tfMarketingStatus")
	public Set<TfAssociate> getTfAssociates() {
		return this.tfAssociates;
	}

	public void setTfAssociates(Set<TfAssociate> tfAssociates) {
		this.tfAssociates = tfAssociates;
	}

    @Override
    public String toString() {
        return "TfMarketingStatus [tfMarketingStatusId=" + tfMarketingStatusId + ", tfMarketingStatusName="
                + tfMarketingStatusName + "]";
    }

}
