package com.revature.entity;
// Generated Nov 7, 2017 9:24:46 PM by Hibernate Tools 5.2.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TfUser generated by hbm2java
 */
@Entity
@Table(name = "TF_USER", schema = "ADMIN")
public class TfUser implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 706405344864879997L;
	private BigDecimal tfUserId;
	private TfRole tfRole;
	private String tfUsername;
	private String tfHashpassword;

	public TfUser() {
	}

	public TfUser(BigDecimal tfUserId) {
		this.tfUserId = tfUserId;
	}

	public TfUser(BigDecimal tfUserId, TfRole tfRole, String tfUserUsername, String tfUserHashpassword) {
		this.tfUserId = tfUserId;
		this.tfRole = tfRole;
		this.tfUsername = tfUserUsername;
		this.tfHashpassword = tfUserHashpassword;
	}

	@Id

	@Column(name = "TF_USER_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getTfUserId() {
		return this.tfUserId;
	}

	public void setTfUserId(BigDecimal tfUserId) {
		this.tfUserId = tfUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TF_ROLE_ID")
	public TfRole getTfRole() {
		return this.tfRole;
	}

	public void setTfRole(TfRole tfRole) {
		this.tfRole = tfRole;
	}

	@Column(name = "TF_USERNAME", length = 20)
	public String getTfUserUsername() {
		return this.tfUsername;
	}

	public void setTfUserUsername(String tfUserUsername) {
		this.tfUsername = tfUserUsername;
	}

	@Column(name = "TF_HASHPASSWORD", length = 200)
	public String getTfUserHashpassword() {
		return this.tfHashpassword;
	}

	public void setTfUserHashpassword(String tfUserHashpassword) {
		this.tfHashpassword = tfUserHashpassword;
	}

}
